'use client';

import { useEffect } from 'react';

/**
 * Explicitly registers the next-pwa generated service worker.
 * next-pwa also injects registration via webpack, but this component
 * acts as a reliable fallback to ensure the SW is always registered.
 */
export function ServiceWorkerRegistration() {
  useEffect(() => {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

    // Register the service worker generated by next-pwa
    window.addEventListener('load', () => {
      navigator.serviceWorker
        .register('/sw.js', { scope: '/' })
        .then((reg) => {
          console.log('[SW] Registered:', reg.scope);
          // Check for updates
          reg.addEventListener('updatefound', () => {
            const newWorker = reg.installing;
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  console.log('[SW] New version available, reload to update.');
                }
              });
            }
          });
        })
        .catch((err) => console.error('[SW] Registration failed:', err));
    });
  }, []);

  return null;
}
