-- =====================================================
-- DISABLE RLS ON ALL TABLES
-- =====================================================
-- This file is kept for backwards compatibility.
-- RLS is already disabled inline in 01_schema.sql.
-- Running this again is safe (idempotent).
-- =====================================================

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE org_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_inquiries DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_favorites DISABLE ROW LEVEL SECURITY;
ALTER TABLE lost_found_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE lost_found_claims DISABLE ROW LEVEL SECURITY;
ALTER TABLE communities DISABLE ROW LEVEL SECURITY;
ALTER TABLE community_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE community_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE community_post_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE notices DISABLE ROW LEVEL SECURITY;
ALTER TABLE notice_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE indoor_maps DISABLE ROW LEVEL SECURITY;
ALTER TABLE points_of_interest DISABLE ROW LEVEL SECURITY;
ALTER TABLE navigation_routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_interested DISABLE ROW LEVEL SECURITY;
ALTER TABLE quick_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE feed_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE feed_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE feedback DISABLE ROW LEVEL SECURITY;
